server:
  port: 8078
spring:
  application:
    name: provider-demo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true